compile = "dotnet publish -c Release --self-contained --output bin/run"
run = "./bin/run/calculator"
watch = ["*.fs", "*.fsl", "*.fsy"]
ignore = [
    "Parser.fs",
    "Lexer.fs",
    "predicates/Parser.fs",
    "predicates/Lexer.fs",
]
